name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      AWS_STACK_NAME: Dnw-Website
      AWS_S3_BUCKET: dnw-templates-2022
      AWS_DISTRIBUTION_ID: E2LR1K2KPCV2U8
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Install dotnet lambda tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      
      - name: Deploy to Lambda
        run: |
          dotnet lambda deploy-serverless \
            --stack-name $AWS_STACK_NAME \
            --s3-bucket $AWS_S3_BUCKET \
            --region $AWS_REGION

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --region $AWS_REGION \
            --distribution-id $AWS_DISTRIBUTION_ID \
            --paths "/*"